services:
  - type: web
    name: smrithi-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app
    envVars:
      - key: PORT
        value: 10000
